### ISSUE TITLE
[Regression]Quickpick used for Deploy command is flashing and not giving user a chance to provide input

### ISSUE THREAD

**Issue by bfitzpat** [camel-tooling/vscode-camelk#106]
This week an error cropped up in VS Code 1.38.0 that causes the integration type dropdown to not function properly. It flashes and steps through, not giving the user an opportunity to make a selection. It was also brought up that some of that code is unnecessarily complex, so it needs to be streamlined in the process.

**Comment by bfitzpat** [comment]
https://github.com/camel-tooling/vscode-camelk/pull/107 fixes the issue

**Comment by apupier** [comment]
I think I found the original reason because quickPick is working in our othe rplugins.
it is due to the outputchannel which is always shown https://github.com/camel-tooling/vscode-camelk/commit/c5bd8217876b8161192b4307795e5a7ec750f1ff#diff-45961516239bc4b63c0fc662708b0e70R148 on each message. Which is making the focus to be lost.

it explains:
- it doesn't disappear anymore which ignoreFocusOut to true
- the up/down arrow not working when ignoreFocusOut set to true

**Comment by djelinek** [comment]
verified - Tooling for Apache Camel K by Red Hat (marketplace version 0.0.9)
