### ISSUE TITLE
Do not pollute all non Camel-K groovy/java/xml/kotlin/js files with Camel-K contextual menus

### ISSUE THREAD

**Issue by apupier** [camel-tooling/vscode-camelk#7]
currently all groovy files will have the Camel-K menu. Only the Camel-K groovy files should have it

**Comment by bfitzpat** [comment]
https://github.com/camel-tooling/camel-language-server/pull/248#issuecomment-511412591

**Comment by bfitzpat** [comment]
As this particular issue came up in a different conversation, I wanted to capture my thoughts here where it made the most sense.

First, though all .java, .xml, .js, .groovy, and .kts files will automatically add the "Start Apache Camel K Integration" menu when the Camel K extension is enabled, we have moved it so it is less in the way. It now shows up towards the bottom of the context menu when you right-click on one of those files in the Explorer files view. 

![image](https://user-images.githubusercontent.com/530878/63433216-01b15400-c3e0-11e9-8eb4-ec4c55ac347e.png)

We have a similar issue now with .properties files, where we've added menus to add Kubernetes ConfigMap and Secrets. But again, those menus have been shoved to near the bottom to keep them out of the way as much as possible.

![image](https://user-images.githubusercontent.com/530878/63434348-24446c80-c3e2-11e9-8d33-24fe60ef7456.png)

We are far from the only ones polluting that menu. (See "Create Maven Project"? It's on EVERY file.)

As such, it is not as in the way as it used to be -- therefore not as much of an obstacle to be overcome.

Second, though we have added some Camel LSP features to other languages to support Camel K, I don't believe we should rely on the modeline (i.e. // camel-k: language=groovy) or file naming (i.e. integration.camelk.groovy) to control whether the menu appears or not. 

These requirements are NOT requirements of Camel K, but are instead hardcoded ways to force the tooling to see them as Camel K related. The runtime doesn't care if they are in place or not. As such, I think we're putting an artificial limitation on the files simply because it is more convenient for us on the tooling side. If we use this artificial limiter, I think we're imposing a constraint on the user that may not be appreciated by the users of the runtime itself. 

I believe that by moving the menus to a less obtrusive location in the pop-up menu, we have addressed the spirit of this issue if not the specific use case.

**Comment by apupier** [comment]
> We have a similar issue now with .properties files, where we've added menus to add Kubernetes ConfigMap and Secrets. But again, those menus have been shoved to near the bottom to keep them out of the way as much as possible.

for properties file, I think it is fine because they can always to be pushed as config map or secrets to a Kubernetes instance.

**Comment by apupier** [comment]
> We are far from the only ones polluting that menu. (See "Create Maven Project"? It's on EVERY file.)

Don't watch people doing bad things. better to try to do better. Worth reporting a bug.

**Comment by apupier** [comment]
> As such, it is not as in the way as it used to be -- therefore not as much of an obstacle to be overcome.

good point

**Comment by apupier** [comment]
> Second, though we have added some Camel LSP features to other languages to support Camel K, I don't believe we should rely on the modeline (i.e. // camel-k: language=groovy) or file naming (i.e. integration.camelk.groovy) to control whether the menu appears or not.
> 
> These requirements are NOT requirements of Camel K, but are instead hardcoded ways to force the tooling to see them as Camel K related. The runtime doesn't care if they are in place or not. As such, I think we're putting an artificial limitation on the files simply because it is more convenient for us on the tooling side. If we use this artificial limiter, I think we're imposing a constraint on the user that may not be appreciated by the users of the runtime itself.

they are good practice that we try to setup.
It is more convenient for tooling to provide a better experience to our users.
As a comparison, what would you expect if I have a java file not having .java extension. Would you expect the java tooling to work?
In this case, i think the Java compiler is even forcing users to have .java extension. I believe the good way would even be to force the runtime to have a more constrained convention.

What is happening when the file is not a Camel-K one and user is trying to deploy? it is not working and there is not even an easy to understand error reported.

I really think providing extra menu causing errors is bringing a worse user experience than to force users to have modeline or filenaming, which are now available directly in Camel-K examples.

**Comment by bfitzpat** [comment]
> they are good practice that we try to setup.

I disagree with this, but don't have anything solid to back that up. I would like to get some feedback from our User Experience (UX) folks to see if they have a recommendation. 

>As a comparison, what would you expect if I have a java file not having .java extension. Would you expect the java tooling to work?

This is a false argument, as the Java runtime requires certain conditions for Java files to compile and run. From the "javac" docs, there is a hard requirement for Java files to comply with a particular naming convention. "Source code file names must have .java suffixes, class file names must have .class suffixes, and both source and class files must have root names that identify the class. For example, a class called MyClass would be written in a source file called MyClass.java and compiled into a bytecode class file called MyClass.class." -- https://docs.oracle.com/javase/7/docs/technotes/tools/windows/javac.html

Comparing that with Camel K, it lists a similar set of supported files, with specific file extensions mentioned in the documentation - https://github.com/apache/camel-k#not-just-java

We on the other hand are adding a constraint of ".camelk.groovy" which is not required by the runtime. If we are looking for a tighter constraint on the runtime, we should ask for one upstream from us rather than imposing an artificial one downstream. Let's open an issue to get that resolved if that's the case.

Our goal is to support the runtime, not put convenient limitations on it for our own use. 

>What is happening when the file is not a Camel-K one and user is trying to deploy? it is not working and there is not even an easy to understand error reported.

Again, if this is the case (and I'm positive it is), I believe we should put the onus on the runtime team to do a check when they try to deploy the file. Let's open an issue to get that resolved as well.

>I really think providing extra menu causing errors is bringing a worse user experience than to force users to have modeline or filenaming, which are now available directly in Camel-K examples.

To clarify this, modeline is now available upstream in the examples https://github.com/apache/camel-k/tree/master/examples but there are no examples with a ".camelk.*" pattern to file naming.

**Comment by apupier** [comment]
> > As a comparison, what would you expect if I have a java file not having .java extension. Would you expect the java tooling to work?
> 
> This is a false argument, as the Java runtime requires certain conditions for Java files to compile and run. From the "javac" docs, there is a hard requirement for Java files to comply with a particular naming convention. "Source code file names must have .java suffixes, class file names must have .class suffixes, and both source and class files must have root names that identify the class. For example, a class called MyClass would be written in a source file called MyClass.java and compiled into a bytecode class file called MyClass.class." -- https://docs.oracle.com/javase/7/docs/technotes/tools/windows/javac.html
> 
> Comparing that with Camel K, it lists a similar set of supported files, with specific file extensions mentioned in the documentation - https://github.com/apache/camel-k#not-just-java
> 
> We on the other hand are adding a constraint of ".camelk.groovy" which is not required by the runtime. If we are looking for a tighter constraint on the runtime, we should ask for one upstream from us rather than imposing an artificial one downstream. Let's open an issue to get that resolved if that's the case.
> 
> Our goal is to support the runtime, not put convenient limitations on it for our own use.

it is exactly my point. This should be a runtime constraint :-)
the fact that Java files requires a .java extension is an arbitrary constraint to help all toolings (compiler, IDEs)

I already asked an discussed it but for now they don't really see the interest. I think the focus is not yet on tooling.

**Comment by apupier** [comment]
it seems to not be possible to implement it currently with limited capabilities of VS Code without breaking other functionalities:
- _when_ clause for menu (like for all other contribution points) cannot use specific code, it requires to rely on a predefined set of contextual values. The only interesting one is _resourceLangId_ (aka language mode)
- a file cannot have 2 different language modes, when competing language modes, one will be picked up - randomly - by VS Code.
- a language type cannot inherit from another
- the combination of the 2 previous points implies that if using specific language mode for Camel K files, we are loosing all basic greatness for the "original" language (xml, java, yaml, groovy...). Unless we reimplement everything of course, which is a non-viable option.

Consequently, i think we can forget about this feature even if it would have avoided a lot of confusions to users. To limit that, I think we should improve feedback error when the command is used on a non Camel K files.
